eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

spring:
  application:
    name: service-rubbish
  datasource:
    name: rubbish_category
    url: jdbc:mysql://47.101.206.174:3306/rubbish_category?useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: zc123456

    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  port: 9010
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.school.schoolrubbish.pojo

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
